var nom = "Judit";
var cognom1 = "Arias";
var cognom2 = "Piferrer";
var dia = 15;
var mes = 01;
var any = 2020;
document.write(cognom1 + " " + cognom2 + ", " + nom + " ");
console.log(cognom1 + " " + cognom2 + ", " + nom);
document.write(dia + "/" + mes + "/" + any);
console.log(dia + "/" + mes + "/" + any);