var ciutat1 = prompt("Escriu el nom de la primera ciutat");
var ciutat2 = prompt("Escriu el nom de la segona ciutat");
var ciutat3 = prompt("Escriu el nom de la tercera ciutat");
var ciutat4 = prompt("Escriu el nom de la quarta ciutat");
var ciutat5 = prompt("Escriu el nom de la cinquena ciutat");
var ciutat6 = prompt("Escriu el nom de la sisena ciutat");
var Aciutat1 = (ciutat1.length);
Aciutat1 = Array.from(ciutat1);
Aciutat1.forEach(Mostra);
document.getElementById("resultat").innerHTML += " - ";
var a = Aciutat1.reverse();
a.forEach(Mostra);
document.getElementById("resultat").innerHTML += "<br>";
var Aciutat2 = (ciutat2.length);
Aciutat2 = Array.from(ciutat2);
Aciutat2.forEach(Mostra);
document.getElementById("resultat").innerHTML += " - ";
var b = Aciutat2.reverse();
b.forEach(Mostra);
document.getElementById("resultat").innerHTML += "<br>";
var Aciutat3 = (ciutat3.length);
Aciutat3 = Array.from(ciutat3);
Aciutat3.forEach(Mostra);
document.getElementById("resultat").innerHTML += " - ";
var c = Aciutat3.reverse();
c.forEach(Mostra);
document.getElementById("resultat").innerHTML += "<br>";
var Aciutat4 = (ciutat4.length);
Aciutat4 = Array.from(ciutat4);
Aciutat4.forEach(Mostra);
document.getElementById("resultat").innerHTML += " - ";
var d = Aciutat4.reverse();
d.forEach(Mostra);
document.getElementById("resultat").innerHTML += "<br>";
var Aciutat5 = (ciutat5.length);
Aciutat5 = Array.from(ciutat5);
Aciutat5.forEach(Mostra);
document.getElementById("resultat").innerHTML += " - ";
var e = Aciutat5.reverse();
e.forEach(Mostra);
document.getElementById("resultat").innerHTML += "<br>";
var Aciutat6 = (ciutat6.length);
Aciutat6 = Array.from(ciutat6);
Aciutat6.forEach(Mostra);
document.getElementById("resultat").innerHTML += " - ";
var f = Aciutat6.reverse();
f.forEach(Mostra);
document.getElementById("resultat").innerHTML += "<br>";
function Mostra(x){
    document.getElementById("resultat").innerHTML += x;
}